In [1]:
import json
from json2html import *
from IPython.display import HTML
import pandas
import numpy
import os, sys
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)
from trec_utils import utils, running, evaluation

In [2]:
config = utils.load_config()

In [3]:
topics_all = utils.get_topics('../input_files/2019.topics.xml')
qrels_all = utils.get_qrels('../input_files/2018.abstracts.sorted.qrels')

In [4]:
topics_all

,topic,disease,gene,gene1,gene2,gene3,extra_inf,sex,age,age_group
1,1,melanoma,BRAF (E586K),BRAF,E586K,,variation,female,64,aged
2,2,cholangiocarcinoma,BRAF (V600E),BRAF,V600E,,variation,male,64,aged
3,3,prostate cancer,ATM deletion,ATM deletion,,,,male,50,aged
4,4,gastric cancer,ERBB2 amplification,ERBB2 amplification,,,,male,64,aged
5,5,cervical cancer,ERBB2 (S310Y),ERBB2,S310Y,,variation,female,45,aged
6,6,non-small cell lung cancer,EGFR (D770N),EGFR,D770N,,variation,female,54,aged
7,7,non-small cell lung cancer,EGFR (T790M),EGFR,T790M,,variation,male,50,aged
8,8,bladder cancer,FGFR3 (S249C),FGFR3,S249C,,variation,male,64,aged
9,9,gastrointestinal stromal tumor,KIT (exon 9 502_503 duplication),KIT,exon 9 502_503 duplication,,variation,male,58,aged
10,10,mucosal melanoma,"KIT (L576P), KIT amplification",KIT,L576P,KIT amplification,variation,female,62,aged
11,11,gastrointestinal stromal tumor,PDGFRA (D842V),PDGFRA,D842V,,variation,female,56,aged
12,12,inflammatory myofibroblastic tumor,RANBP2-ALK fusion,RANBP2,ALK,,fusion,female,32,adult
13,13,lung adenocarcinoma,EZR-ROS1 fusion,EZR,ROS1,,fusion,male,72,aged
14,14,colon cancer,MLH1 methylation suppression (microsatellite i...,MLH1 methylation suppression,microsatellite instability,,variation,male,68,aged
15,15,lung adenocarcinoma,"KRAS (G12V), high tumor mutational burden",KRAS,G12V,high tumor mutational burden,variation,male,57,aged
16,16,papillary thyroid carcinoma,BRAF (V600E),BRAF,V600E,,variation,female,51,aged
17,17,glioblastoma,IDH1 (R132H),IDH1,R132H,,variation,male,50,aged
18,18,lung adenocarcinoma,SND1-BRAF fusion,SND1,BRAF,,fusion,female,54,aged
19,19,colon cancer,ERBB2 amplification,ERBB2 amplification,,,,female,45,aged
20,20,pancreatic cancer,BRCA2,BRCA2,,,,male,50,aged
21,21,gastrointestinal stromal tumor,KIT (V654A),KIT,V654A,,variation,male,70,aged
22,22,colon cancer,PIK3CA (E545K),PIK3CA,E545K,,variation,female,45,aged
23,23,breast cancer,AURKA amplification,AURKA amplification,,,,female,70,aged
24,24,cholangiocarcinoma,PIK3CA (1047H),PIK3CA,1047H,,variation,male,62,aged
25,25,melanoma,NRAS (Q61H),NRAS,Q61H,,variation,male,32,adult
26,26,squamous cell lung cancer,FGFR1 amplification,FGFR1 amplification,,,,female,65,aged
27,27,non-small cell lung cancer,KRAS (G12C),KRAS,G12C,,variation,male,70,aged
28,28,ovarian cancer,BRCA1,BRCA1,,,,female,64,aged
29,29,chondrosarcoma,IDH1,IDH1,,,,female,26,adult
30,30,endometrial cancer,PIK3R1,PIK3R1,,,,female,58,aged
31,31,aortic aneurysm,ACTA2,ACTA2,,,,female,63,aged
32,32,Loeys-Dietz syndrome,TGFBR2,TGFBR2,,,,male,42,adult
33,33,long QT syndrome,KCNQ1,KCNQ1,,,,male,15,adolescent
34,34,Brugada syndrome,SCN5A,SCN5A,,,,female,36,adult
35,35,familial hypercholesterolemia,PCSK9,PCSK9,,,,female,24,adult
36,36,Li-Fraumeni syndrome,TP53,TP53,,,,female,14,adolescent
37,37,dilated cardiomyopathy,LMNA,LMNA,,,,male,32,adult
38,38,Peutz-Jeghers syndrome,STK11,STK11,,,,male,11,child
39,39,long QT syndrome,KCNH2,KCNH2,,,,female,19,adult
40,40,malignant hyperthermia,RYR1,RYR1,,,,male,54,aged

In [5]:
TOPIC = 2
topic = topics_all[(topics_all.topic==TOPIC)]
qrels = utils.qrels_of_topics(qrels_all, topic)
topic

,topic,disease,gene,gene1,gene2,gene3,extra_inf,sex,age,age_group
2,2,cholangiocarcinoma,BRAF (V600E),BRAF,V600E,,variation,male,64,aged

## Best result 2018
-  infNDCG: 0.5621
-  R-prec: 0.3684
-  P@10: 0.7060

# Query 1 - Baseline

In [6]:
run_params = {
    'run_id':'imi_mug_run_1',
    'query_template':'submitted/imi_mug_run_1.json',
    'output_size' : 1000,
}
run, run_params = running.run(topics_all, 'ABSTRACTS', run_params)
#results, aggregated = evaluation.evaluate(qrels[(qrels.relev.isin([2]))], run)
#aggregated

RUN: imi_mug_run_1 TOPICS: 40

In [9]:
run.head(2)

,TOPIC_NO,Q0,ID,RANK,SCORE,RUN_NAME,TITLE
0,1,Q0,24926260,1,62.411500,imi_mug_run_1,Malignant Melanoma with Concurrent BRAF E586K ...
1,1,Q0,29181212,2,47.661484,imi_mug_run_1,Uncommon BRAF Mutations Associated with Durabl...

In [10]:
utils.to_trec_run_file(run, run_params)

# Query 2 - Testings - test_template.json

In [14]:
run_params2 = {
    'run_id':'imi_mug_run_2',
    'query_template':'submitted/imi_mug_run_2.json',
    'output_size' : 1000,
}
run2, run_params2 = running.run(topics_all, 'ABSTRACTS', run_params2)
#results, aggregated = evaluation.evaluate(qrels[(qrels.relev.isin([2]))], run)
#aggregated

RUN: imi_mug_run_2 TOPICS: 40

In [15]:
run2.head(2)

,TOPIC_NO,Q0,ID,RANK,SCORE,RUN_NAME,TITLE
0,1,Q0,24926260,1,62.411500,imi_mug_run_2,Malignant Melanoma with Concurrent BRAF E586K ...
1,1,Q0,29181212,2,47.661484,imi_mug_run_2,Uncommon BRAF Mutations Associated with Durabl...

In [16]:
utils.to_trec_run_file(run2, run_params2)

### Query 2 - with treatments

In [17]:
run_params2_treatment = {
    'run_id':'imi_mug_run_2_treatment',
    'query_template':'submitted/imi_mug_run_2.json',
    'output_size' : 1500,
}
run2_treatment, run_params2_treatment = running.run(topics_all, 'ABSTRACTS', run_params2_treatment)

RUN: imi_mug_run_2_treatment TOPICS: 40

In [18]:
run2_treatment = utils.run_with_treatments(run2_treatment)

START Fri Aug  2 12:00:15 2019

/home/pablo/git/plopezgarcia/trec-2019-precision-medicine/python-experiments/trec_utils/utils.py:186: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  run['TREATMENTS_1'][index], run['TREATMENTS_2'][index] = treatments_sorted[0][0], treatments_sorted[1][0]
/home/pablo/git/plopezgarcia/trec-2019-precision-medicine/python-experiments/trec_utils/utils.py:188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  run['TREATMENTS_1'][index] = treatments_sorted[0][0]
/home/pablo/git/plopezgarcia/trec-2019-precision-medicine/python-experiments/trec_utils/utils.py:184: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  run['TREATMENTS_1'][index], run['TREATMENTS_2'][index], run['TREATMENTS_3'][index] = treatments_sorted[0][0], treatments_sorted[1][0], treatments_sorted[2][0]

FINISH Fri Aug  2 13:08:24 2019

In [19]:
run2_treatment.head(2)

,TOPIC_NO,Q0,ID,RANK,SCORE,RUN_NAME,TITLE,TREATMENTS_1,TREATMENTS_2,TREATMENTS_3
0,1,Q0,24926260,1,62.411500,imi_mug_run_2_treatment,Malignant Melanoma with Concurrent BRAF E586K ...,,,
1,1,Q0,29181212,2,47.661484,imi_mug_run_2_treatment,Uncommon BRAF Mutations Associated with Durabl...,,,

In [22]:
utils.to_trec_run_file_with_treatments(run2_treatment, run_params2_treatment)

# Query 3 - Add keywords - test_template_2.json

In [23]:
run_params3 = {
    'run_id':'imi_mug_run_3',
    'query_template':'submitted/imi_mug_run_3.json',
    'output_size' : 1000,
}
run3, run_params3 = running.run(topics_all, 'ABSTRACTS', run_params3)
#results, aggregated = evaluation.evaluate(qrels[(qrels.relev.isin([2]))], run)
#aggregated

RUN: imi_mug_run_3 TOPICS: 40

In [24]:
run3.head(2)

,TOPIC_NO,Q0,ID,RANK,SCORE,RUN_NAME,TITLE
0,1,Q0,24926260,1,61.480373,imi_mug_run_3,Malignant Melanoma with Concurrent BRAF E586K ...
1,1,Q0,24893747,2,59.026592,imi_mug_run_3,A combination of p300 and Braf expression in t...

In [25]:
utils.to_trec_run_file(run3, run_params3)

### Query 3 - with treatments

In [26]:
run_params3_treatment = {
    'run_id':'imi_mug_run_3_treatment',
    'query_template':'submitted/imi_mug_run_3.json',
    'output_size' : 1500,
}
run3_treatment, run_params3_treatment = running.run(topics_all, 'ABSTRACTS', run_params3_treatment)
#results, aggregated = evaluation.evaluate(qrels[(qrels.relev.isin([2]))], run)
#aggregated

RUN: imi_mug_run_3_treatment TOPICS: 40

In [27]:
run3_treatment = utils.run_with_treatments(run3_treatment)

START Fri Aug  2 14:05:30 2019

/home/pablo/git/plopezgarcia/trec-2019-precision-medicine/python-experiments/trec_utils/utils.py:186: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  run['TREATMENTS_1'][index], run['TREATMENTS_2'][index] = treatments_sorted[0][0], treatments_sorted[1][0]
/home/pablo/git/plopezgarcia/trec-2019-precision-medicine/python-experiments/trec_utils/utils.py:188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  run['TREATMENTS_1'][index] = treatments_sorted[0][0]
/home/pablo/git/plopezgarcia/trec-2019-precision-medicine/python-experiments/trec_utils/utils.py:184: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  run['TREATMENTS_1'][index], run['TREATMENTS_2'][index], run['TREATMENTS_3'][index] = treatments_sorted[0][0], treatments_sorted[1][0], treatments_sorted[2][0]

FINISH Fri Aug  2 15:14:03 2019

In [28]:
run3_treatment.head(2)

,TOPIC_NO,Q0,ID,RANK,SCORE,RUN_NAME,TITLE,TREATMENTS_1,TREATMENTS_2,TREATMENTS_3
0,1,Q0,24926260,1,61.480373,imi_mug_run_3_treatment,Malignant Melanoma with Concurrent BRAF E586K ...,,,
1,1,Q0,24893747,2,59.026592,imi_mug_run_3_treatment,A combination of p300 and Braf expression in t...,drugs,vemurafenib,

In [29]:
utils.to_trec_run_file_with_treatments(run3_treatment, run_params3_treatment)